<?php

/**
 * @file
 * Contains jbi_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jbi_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jbi_events module.
    case 'help.page.jbi_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides events and subscriptions storage entities.') . '</p>';
      return $output;

    default:
  }
}
